name: Documentation
description: Request improvements to documentation
title: '[Docs] '
labels: [documentation]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Notionista documentation! Let us know what documentation is missing or unclear.

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What documentation issue are you reporting?
      placeholder: Is something unclear, missing, or incorrect in our docs?
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where in the documentation is the issue? (URL or file path)
      placeholder: 'e.g., docs/core-concepts.md or https://...'
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What would help clarify or improve the documentation?
      placeholder: Propose how we could improve this documentation
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Examples, code snippets, or external references

  - type: checkboxes
    id: checks
    attributes:
      label: Verification
      options:
        - label: I have read the relevant documentation
          required: true
