name: Feature Request
description: Suggest a new feature for Notionista
title: '[Feature] '
labels: [enhancement, triage]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement! Please provide a clear description of the feature you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a limitation?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe alternative solutions you've considered

  - type: textarea
    id: use_case
    attributes:
      label: Use Case / Example
      description: Provide a concrete example of how this feature would be used
      placeholder: |
        Example code or scenario showing how this feature would be used
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Related issues, discussions, or external references

  - type: checkboxes
    id: checks
    attributes:
      label: Verification
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with the project scope
          required: false
